### ISSUE TITLE
UI Enhancements

### ISSUE THREAD

**Issue by akashchouhan16** [Blumea/Blumea-Playground#1]
- [x] Title of the web app to be updated to: **Blumea Playground**
- [x] #2
- [x] Output table rows to be increased to **3 or 4 per view**.
- [x] Disable dropdowns must be desaturated to make it visually obvious.
- [x] Could use toast notifications in case of alerts or errors. _[optional]_
- [x] Include a component-level animation while the table data is updated.
- [x] Preloader animation same across all the UI apps. (Blumea-UI, Blumea-Docs, Blumea-Playground)
- [x] #3

**Comment by ayan-IN** [comment]
Closing UI Updates :rocket:

**Comment by akashchouhan16** [comment]
Cheers @ayan-IN 🥂

**Comment by ayan-IN** [comment]
😋
